# Generated by Django 5.2 on 2025-04-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lokalita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(max_length=100, verbose_name='Město')),
                ('cast', models.CharField(blank=True, max_length=100, null=True, verbose_name='Městská část')),
            ],
            options={
                'verbose_name': 'Lokalita',
                'verbose_name_plural': 'Lokality',
                'ordering': ['mesto', 'cast'],
                'unique_together': {('mesto', 'cast')},
            },
        ),
        migrations.CreateModel(
            name='MajitelNemovitosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamky', models.TextField(blank=True, default='')),
                ('klient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Nemovitost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=300)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popis', models.TextField(blank=True, default='')),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='nemovitosti/')),
                ('rozloha', models.PositiveIntegerField(blank=True, help_text='Rozloha v m²', null=True)),
                ('typ', models.CharField(choices=[('byt', 'Byt'), ('dum', 'Dům'), ('pozemek', 'Pozemek')], default='byt', max_length=100)),
                ('stav', models.CharField(choices=[('novostavba', 'Novostavba'), ('k_rekonstrukci', 'K rekonstrukci'), ('dobry', 'Dobrý stav')], default='dobry', max_length=100)),
                ('lokalita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lokalita', verbose_name='Lokalita')),
                ('majitel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.majitelnemovitosti')),
            ],
        ),
        migrations.CreateModel(
            name='Obrazek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='nemovitosti/')),
                ('popis', models.CharField(blank=True, max_length=255, null=True)),
                ('nemovitost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrazky', to='main.nemovitost')),
            ],
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='dalsi_obrazky',
            field=models.ManyToManyField(blank=True, related_name='nemovitosti', to='main.obrazek'),
        ),
        migrations.CreateModel(
            name='Transakce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_transakce', models.DateField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ_transakce', models.CharField(choices=[('Koupě', 'Koupě'), ('Prodej', 'Prodej')], max_length=50)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.klient')),
                ('nemovitost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nemovitost')),
            ],
        ),
    ]
