# Generated by Django 5.1.7 on 2025-03-28 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lokalita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('adresa', models.CharField(blank=True, default='', max_length=300)),
                ('mesto', models.CharField(blank=True, default='', max_length=100)),
                ('psc', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MajitelNemovitosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamky', models.TextField(blank=True, default='')),
                ('klient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Nemovitost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=300)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popis', models.TextField(blank=True, default='')),
                ('lokalita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lokalita')),
                ('majitel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.majitelnemovitosti')),
            ],
        ),
        migrations.CreateModel(
            name='Transakce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_transakce', models.DateField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ_transakce', models.CharField(choices=[('Koupě', 'Koupě'), ('Prodej', 'Prodej')], max_length=50)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.klient')),
                ('nemovitost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nemovitost')),
            ],
        ),
    ]
