# Generated by Django 5.2 on 2025-04-21 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nemovitost',
            name='cena',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cast'),
        ),
        migrations.AddField(
            model_name='cast',
            name='mesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casti', to='main.mesto'),
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='mesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mesto'),
        ),
    ]
