# Generated by Django 5.1.7 on 2025-04-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nemovitost',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='nemovitosti/'),
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='rozloha',
            field=models.PositiveIntegerField(blank=True, help_text='Rozloha v m²', null=True),
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='stav',
            field=models.CharField(choices=[('novostavba', 'Novostavba'), ('k_rekonstrukci', 'K rekonstrukci'), ('dobry', 'Dobrý stav')], default='dobry', max_length=100),
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='typ',
            field=models.CharField(choices=[('byt', 'Byt'), ('dum', 'Dům'), ('pozemek', 'Pozemek')], default='byt', max_length=100),
        ),
    ]
