# Generated by Django 5.2 on 2025-04-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cast_mesto_alter_nemovitost_cena_nemovitost_cast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nemovitost',
            name='lokalita',
        ),
    ]
