# Generated by Django 5.1.7 on 2025-04-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nemovitost_obrazek_nemovitost_rozloha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrazek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='nemovitosti/')),
                ('popis', models.CharField(blank=True, max_length=255, null=True)),
                ('nemovitost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrazky', to='main.nemovitost')),
            ],
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='dalsi_obrazky',
            field=models.ManyToManyField(blank=True, related_name='nemovitosti', to='main.obrazek'),
        ),
    ]
