# Generated by Django 5.2 on 2025-04-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_nemovitost_lokalita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lokalita',
        ),
    ]
