# Generated by Django 5.2 on 2025-05-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_lokalita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'ordering': ['mesto', 'nazev'], 'verbose_name_plural': 'Městské části'},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ['jmeno'], 'verbose_name_plural': 'Klienti'},
        ),
        migrations.AlterModelOptions(
            name='majitelnemovitosti',
            options={'verbose_name_plural': 'Majitelé nemovitostí'},
        ),
        migrations.AlterModelOptions(
            name='mesto',
            options={'ordering': ['nazev'], 'verbose_name_plural': 'Města'},
        ),
        migrations.AlterModelOptions(
            name='nemovitost',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Nemovitosti'},
        ),
        migrations.AlterModelOptions(
            name='obrazek',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Obrázky'},
        ),
        migrations.AlterModelOptions(
            name='transakce',
            options={'verbose_name_plural': 'Transakce'},
        ),
    ]
