  services:
    web:
      restart: unless-stopped
      build: .
      pull_policy: build
      # ports:
      #   - 8000:80
      volumes:
        - ./prj:/app

      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.wt-mb-http.rule=Host(`mb.gawt.dtcloud.cz`)"
        - "traefik.http.routers.wt-mb-http.entrypoints=web"
        - "traefik.http.routers.wt-mb-http.middlewares=wt-mb-redirect-https@docker"

        - "traefik.http.middlewares.wt-mb-redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.wt-mb-redirect-https.redirectscheme.permanent=true"

        - "traefik.http.routers.wt-mb-https.rule=Host(`mb.gawt.dtcloud.cz`)"
        - "traefik.http.routers.wt-mb-https.entrypoints=websecure"
        - "traefik.http.routers.wt-mb-https.tls=true"
        - "traefik.http.routers.wt-mb-https.tls.certresolver=letsencrypt"

    static:
      image: nginx:alpine
      restart: unless-stopped

      volumes:
        - ./prj/staticfiles:/usr/share/nginx/html/static:ro

      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.wt-mb-static-http.rule=Host(`mb.gawt.dtcloud.cz`) && PathPrefix(`/static`)"
        - "traefik.http.routers.wt-mb-static-http.entrypoints=web"
        - "traefik.http.routers.wt-mb-static-http.middlewares=wt-mb-static-redirect-https@docker"

        - "traefik.http.middlewares.wt-mb-static-redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.wt-mb-static-redirect-https.redirectscheme.permanent=true"

        - "traefik.http.routers.wt-mb-static-https.rule=Host(`mb.gawt.dtcloud.cz`) && PathPrefix(`/static`)"
        - "traefik.http.routers.wt-mb-static-https.entrypoints=websecure"
        - "traefik.http.routers.wt-mb-static-https.tls=true"
        - "traefik.http.routers.wt-mb-static-https.tls.certresolver=letsencrypt"

  networks:
    default:
      name: proxy
      external: true